apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-app
  labels:
    app: sentiment-analysis-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-analysis-app
  template:
    metadata:
      labels:
        app: sentiment-analysis-app
    spec:
      containers:
      - name: sentiment-analysis-app
        image: satyamd31/sentiment-analysis-app:{{IMAGE_TAG}}
        ports:
        - containerPort: 5000